/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package responsi2_l0122081_sc;

import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.border.Border;

/**
 *
 * @author franklynical
 */
public class framePinjam extends javax.swing.JFrame {

    /**
     * Creates new form framePinjam
     */
    public framePinjam() {
        AccessXML.readXML();
        initComponents();
        getContentPane().setBackground(new java.awt.Color(57, 54, 70));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IDa = new javax.swing.JTextField(){
            @Override protected void paintComponent(Graphics g) {
                Border b = getBorder();
                if (!isOpaque() && b instanceof RoundedCornerBorder) {
                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setPaint(getBackground());
                    int w = getWidth() - 1;
                    int h = getHeight() - 1;
                    g2.fill(((RoundedCornerBorder) b).getBorderShape(0, 0, w, h));
                    g2.dispose();
                }
                super.paintComponent(g);
            }

            @Override public void updateUI() {
                super.updateUI();
                setOpaque(false);
                setBorder(new RoundedCornerBorder(8));
            }
        }
        ;
        ID = new javax.swing.JTextField(){
            @Override protected void paintComponent(Graphics g) {
                Border b = getBorder();
                if (!isOpaque() && b instanceof RoundedCornerBorder) {
                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setPaint(getBackground());
                    int w = getWidth() - 1;
                    int h = getHeight() - 1;
                    g2.fill(((RoundedCornerBorder) b).getBorderShape(0, 0, w, h));
                    g2.dispose();
                }
                super.paintComponent(g);
            }

            @Override public void updateUI() {
                super.updateUI();
                setOpaque(false);
                setBorder(new RoundedCornerBorder(8));
            }
        }
        ;
        k = new javax.swing.JButton(){
            @Override protected void paintComponent(Graphics g) {
                Border b = getBorder();
                if (!isOpaque() && b instanceof RoundedCornerBorder) {
                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setPaint(getBackground());
                    int w = getWidth() - 1;
                    int h = getHeight() - 1;
                    g2.fill(((RoundedCornerBorder) b).getBorderShape(0, 0, w, h));
                    g2.dispose();
                }
                super.paintComponent(g);
            }

            @Override public void updateUI() {
                super.updateUI();
                setOpaque(false);
                setBorder(new RoundedCornerBorder(8));
            }
        }
        ;
        p = new javax.swing.JButton(){
            @Override protected void paintComponent(Graphics g) {
                Border b = getBorder();
                if (!isOpaque() && b instanceof RoundedCornerBorder) {
                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setPaint(getBackground());
                    int w = getWidth() - 1;
                    int h = getHeight() - 1;
                    g2.fill(((RoundedCornerBorder) b).getBorderShape(0, 0, w, h));
                    g2.dispose();
                }
                super.paintComponent(g);
            }

            @Override public void updateUI() {
                super.updateUI();
                setOpaque(false);
                setBorder(new RoundedCornerBorder(8));
            }
        }
        ;
        jButton3 = new javax.swing.JButton(){
            @Override protected void paintComponent(Graphics g) {
                Border b = getBorder();
                if (!isOpaque() && b instanceof RoundedCornerBorder) {
                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setPaint(getBackground());
                    int w = getWidth() - 1;
                    int h = getHeight() - 1;
                    g2.fill(((RoundedCornerBorder) b).getBorderShape(0, 0, w, h));
                    g2.dispose();
                }
                super.paintComponent(g);
            }

            @Override public void updateUI() {
                super.updateUI();
                setOpaque(false);
                setBorder(new RoundedCornerBorder(8));
            }
        }
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(244, 238, 224));
        jLabel1.setText("ID Anggota");

        jLabel2.setForeground(new java.awt.Color(244, 238, 224));
        jLabel2.setText("ID Buku");

        IDa.setBackground(new java.awt.Color(244, 238, 224));
        IDa.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        IDa.setForeground(new java.awt.Color(109, 93, 110));
        IDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDaActionPerformed(evt);
            }
        });

        ID.setBackground(new java.awt.Color(244, 238, 224));
        ID.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        ID.setForeground(new java.awt.Color(109, 93, 110));

        k.setBackground(new java.awt.Color(244, 238, 224));
        k.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        k.setForeground(new java.awt.Color(109, 93, 110));
        k.setText("Kembalikan");
        k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kMouseClicked(evt);
            }
        });
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });

        p.setBackground(new java.awt.Color(244, 238, 224));
        p.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        p.setForeground(new java.awt.Color(109, 93, 110));
        p.setText("Pinjam");
        p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMouseClicked(evt);
            }
        });
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(244, 238, 224));
        jButton3.setFont(new java.awt.Font("Gotham Light", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(109, 93, 110));
        jButton3.setText("Home");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(p)
                        .addGap(67, 67, 67)
                        .addComponent(k)
                        .addGap(73, 73, 73))))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(k)
                    .addComponent(p))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDaActionPerformed

    private void kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kMouseClicked
        String idBuku = ID.getText();
        String idAnggota = IDa.getText();
        if (idAnggota.matches("[A][T][0-9]{3}")){
            Pinjam.kembalikanBukuTetap(idBuku, idAnggota);
        } else {
            Pinjam.kembalikanBukuBulanan(idBuku, idAnggota);
        }
        AccessXML.writeXML();
    }//GEN-LAST:event_kMouseClicked

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kActionPerformed

    private void pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseClicked
        String idBuku = ID.getText();
        String idAnggota = IDa.getText();
        if (idAnggota.matches("[A][T][0-9]{3}")){
            Pinjam.pinjamBukuTetap(idBuku, idAnggota);
        } else {
            Pinjam.pinjamBukuBulanan(idBuku, idAnggota);
        }
        AccessXML.writeXML();
    }//GEN-LAST:event_pMouseClicked

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        AccessXML.writeXML();
        frameUtama fu = new frameUtama();
        fu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField IDa;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton k;
    private javax.swing.JButton p;
    // End of variables declaration//GEN-END:variables
}
